[honeydb_badhosts]
python.version = python3
python.required = 3.9, 3.13

[honeydb_sensor_data]
python.version = python3
python.required = 3.9, 3.13

[honeydb_badhosts://honeydb]
account = honeydb
disabled = 1
index = honeydb
interval = 1800
python.required = 3.9, 3.13

[honeydb_sensor_data://honeydb]
account = honeydb
disabled = 1
index = honeydb
interval = 60
python.required = 3.9, 3.13
