[honeydb_index]
definition = index=honeydb
iseval = 0

[honeydb_badhost(1)]
args = field
definition = lookup honeydb_badhosts_lookup remote_host AS $field$ OUTPUT count AS honeydb_count, last_seen AS honeydb_last_seen
iseval = 0
