[honeydb_badhosts]
SHOULD_LINEMERGE=false
TIMESTAMP_FIELDS = date
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%:z
MAX_TIMESTAMP_LOOKAHEAD = -1
TZ = UTC
FIELDALIAS-honeydb_badhosts_src = remote_host AS src
EVAL-vendor_product = "HoneyDB"

[honeydb_sensor_data]
INDEXED_EXTRACTIONS = JSON
AUTO_KV_JSON = false
TIMESTAMP_FIELDS = date_time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%:z
MAX_TIMESTAMP_LOOKAHEAD = -1
TZ = UTC
FIELDALIAS-honeydb_sensor_data_src = remote_host AS src
EVAL-signature = if(isnull(event) OR event == "", service, event." ".service)
EVAL-transport = lower(protocol)
EVAL-ids_type = "network"
EVAL-category = lower(service)
EVAL-severity = "informational"
EVAL-vendor_product = "HoneyDB"
