name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Unit tests
      run: make test PYTHON=python3
    - name: Lint
      run: make lint PYTHON=python3
    - name: Build and package
      run: make package PYTHON=python3
    - name: Inspect package
      run: make inspect PYTHON=python3
